export const GET_HOT_POST_REQUEST = 'GET_HOT_POST_REQUEST';
export const GET_HOT_POST_SUCCESS = 'GET_HOT_POST_SUCCESS';
export const GET_HOT_POST_FAILED = 'GET_HOT_POST_FAILED';

export const GET_BEST_POST_REQUEST = 'GET_BEST_POST_REQUEST';
export const GET_BEST_POST_SUCCESS = 'GET_BEST_POST_SUCCESS';
export const GET_BEST_POST_FAILED = 'GET_BEST_POST_FAILED';

export const GET_NEW_POST_REQUEST = 'GET_NEW_POST_REQUEST';
export const GET_NEW_POST_SUCCESS = 'GET_NEW_POST_SUCCESS';
export const GET_NEW_POST_FAILED = 'GET_NEW_POST_FAILED';

export const GET_TOP_POST_REQUEST = 'GET_TOP_POST_REQUEST';
export const GET_TOP_POST_SUCCESS = 'GET_TOP_POST_SUCCESS';
export const GET_TOP_POST_FAILED = 'GET_TOP_POST_FAILED';

export const GET_SUBMISSION_DETAILS_BY_ID_REQUEST = 'GET_SUBMISSION_DETAILS_BY_ID_REQUEST';
export const GET_SUBMISSION_DETAILS_BY_ID_SUCCESS = 'GET_SUBMISSION_DETAILS_BY_ID_SUCCESS';
export const GET_SUBMISSION_DETAILS_BY_ID_FAILED = 'GET_SUBMISSION_DETAILS_BY_ID_FAILED';

export const CLEAR_SUBMISSION_DETAILS = 'CLEAR_SUBMISSION_DETAILS';
